/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:62d27677-dbc9-4c69-b530-cbafd9d53b4c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_txFbIaU9f",
    "aws_user_pools_web_client_id": "73eoh3dgliqi13k25ec0ocvnmd",
    "oauth": {}
};


export default awsmobile;
